sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 003913

  redis:
    host: localhost
    port: 6379
    password: 003913
    database: 0

  wechat:
    appid: wx6a848fdb23a75d3a
    secret: bd972276b72b225aab4e199411b13047